import os

from dotenv import load_dotenv

load_dotenv('.env.prod')
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")

POSTGRES_HOST = os.getenv("POSTGRES_HOST")
print(POSTGRES_HOST)
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
BASE_URL = os.getenv("BASE_URL")
PYTHONPATH = os.getenv("PYTHONPATH")

ADLIYA_API = os.getenv("ADLIYA_API")
ADLIYA_LOGIN=os.getenv("ADLIYA_LOGIN")
ADLIYA_PASSWORD=os.getenv("ADLIYA_PASSWORD")

HYBRID_API = os.getenv("HYBRID_API")
HYBRID_API_TEST = os.getenv("HYBRID_API_TEST")
HYBRID_API_TOKEN = os.getenv("HYBRID_API_TOKEN")

IABS_API = os.getenv("IABS_API")
IABS_LOGIN = os.getenv("IABS_LOGIN")
IABS_SHINA_PASSWORD = os.getenv("IABS_SHINA_PASSWORD")


PLAYMOBILE_API = os.getenv("PLAYMOBILE_API")
PLAYMOBILE_TOKEN = os.getenv("PLAYMOBILE_TOKEN")

SOLIQ_API = os.getenv("SOLIQ_API")
SOLIQ_AUTH_LOGIN = os.getenv("SOLIQ_AUTH_LOGIN")
SOLIQ_AUTH_PASSWORD = os.getenv("SOLIQ_AUTH_PASSWORD")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")


IABS_TEST_HOST = os.getenv('IABS_TEST_HOST')
IABS_TEST_PORT = os.getenv('IABS_TEST_PORT')
IABS_TEST_USER = os.getenv('IABS_TEST_USER')
IABS_TEST_PASSWORD = os.getenv('IABS_TEST_PASSWORD')
IABS_TEST_DB = os.getenv('IABS_TEST_DB')
IABS_TEST_SERVICE_NAME = os.getenv('IABS_TEST_SERVICE_NAME')


IABS_HOST = os.getenv('IABS_HOST')
IABS_PORT = os.getenv('IABS_PORT')
IABS_USER = os.getenv('IABS_USER')
IABS_PASSWORD = os.getenv('IABS_PASSWORD')
IABS_DB = os.getenv('IABS_DB')
IABS_SERVICE_NAME = os.getenv('IABS_SERVICE_NAME')

SSP_API = os.getenv('SSP_API')
SSP_AUTH_LOGIN = os.getenv('SSP_AUTH_LOGIN')
SSP_AUTH_PASSWORD = os.getenv('SSP_AUTH_PASSWORD')

GAROV_API = os.getenv('GAROV_API')
GAROV_AUTH_LOGIN = os.getenv('GAROV_AUTH_LOGIN')
GAROV_AUTH_PASSWORD = os.getenv('GAROV_AUTH_PASSWORD')

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')